#!/bin/bash

# Get program file name as cli arg
file_name=$1

# Run tokenizer, get tokens
tokens=$(python3 tokenizer.py $file_name)

# Surround tokens with square brackets
tokens_in_brackets="["$(echo -e "$tokens")"]"

# Run the Prolog program dcg.
# swipl -f dcg -g program $tokens_in_brackets []

# echo $tokens_in_brackets