#!/bin/bash

cwd="$(dirname "$0")"

# Get program file name as cli arg
file_name=$1

# Run tokenizer, get tokens
tokens=$(python3 ${cwd}/tokenizer.py $file_name)

# Surround tokens with square brackets
tokens_in_brackets="["$(echo -e "$tokens")"]"

# Run the Prolog program dcg.
parse_tree=$(swipl -s ${cwd}/parse_tree -g "program(P,$tokens_in_brackets,[]),print(P)"  -t "halt")

echo $parse_tree